### ISSUE TITLE
Pull request with changed 49918 lines estimated as `size/XS`

### ISSUE THREAD

**Issue by dgroup** [kkohtaka/gh-actions-pr-size#15]
**Test case:**
In one of my projects we have to add temporary generated model classes (it would be removed once other team provide a library) and the scope of changes is `+49,918` added lines,  `−124` removed lines
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1651114/167350419-64ba3585-a54b-4d48-8512-762f008a2197.png">
were estimated as pull request with size XS
<img width="481" alt="image" src="https://user-images.githubusercontent.com/1651114/167351212-826fd61a-6be1-4955-9bc1-58bc193b3273.png">
<img width="317" alt="image" src="https://user-images.githubusercontent.com/1651114/167351279-0f003e89-987e-4b97-a7f7-a5d4fda09ff8.png">

The action config:
```
name: "Quality Gate"
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
jobs:
  check_pr_size:
    name: Check Pull Request size
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # Estimate pull request size and mark it by label: https://github.com/kkohtaka/gh-actions-pr-size
      - name: Estimate pull request
        uses: kkohtaka/gh-actions-pr-size@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Logs
```bash
Run kkohtaka/gh-actions-pr-size@v1.0.1
/usr/bin/docker run --name tbd --label 08450d --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_JOB -e 
GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e 
GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e 
GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e 
GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e 
GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e 
RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e 
ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v 
"/home/runner/work/_temp/_github_workflow":"/github/workflow" -v 
"/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/tbd/tbd":"/github/workspace" tbd:tbd    
2022-05-05T08:05:29.378Z	INFO	gh-actions-pr-size/main.go:52	Successfully read an event payload	{"owner": "tbd", "repo": "tbd", "number": 85}
2022-05-05T08:05:29.804Z	INFO	gh-actions-pr-size/main.go:71	Got a size of a pull request	{"size": "XS"}
2022-05-05T08:05:30.693Z	INFO	gh-actions-pr-size/main.go:77	Set a label to represent a pull request size	{"size": "XS"}
```
**Actual result:** Label `size/XS` set to pull request
**Expected result:** Label `size/XXL` set to pull request
**Workaround:** Not found
**Similar case:** Not found
