### ISSUE TITLE
Error when Pull request is raised by @dependabot

### ISSUE THREAD

**Issue by dgroup** [kkohtaka/gh-actions-pr-size#9]
**Test case:**
The workflow configuration fails when [dependabot](https://github.com/apps/dependabot) raises the pull requests for dependencies upgrade:
```
name: "Quality Gate"
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: '20 7 * * 6'
jobs:
  check_pr_size:
    name: Check Pull Request size
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # Estimate pull request size and mark it by label: https://github.com/kkohtaka/gh-actions-pr-size
      - name: Estimate pull request
        uses: kkohtaka/gh-actions-pr-size@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
An example of failure message
```bash
Run kkohtaka/gh-actions-pr-size@v1.0.0
/usr/bin/docker run --name tbd --label 294b31 --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_JOB -e 
GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e 
GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e 
GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e 
GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e 
GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e 
RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e 
ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/tbd/tbd":"/github/workspace" tbd:tbd
2022-05-04T01:29:16.459Z	INFO	gh-actions-pr-size/main.go:52	Successfully read an event payload	{"owner": "tbd", "repo": "tbd", "number": 80}
2022-05-04T01:29:16.791Z	INFO	gh-actions-pr-size/main.go:71	Got a size of a pull request	{"size": "XS"}
2022-05-04T01:29:17.263Z	ERROR	gh-actions-pr-size/github.go:126	Failed to add a label to a pull request	{"owner": "tbd", "repo": "tbd", "number": 80, "label": "size/XS", "error": "POST https://api.github.com/repos/tbd/tbd/issues/80/labels: 403 Resource not accessible by integration []"}
main.setLabelOnPullRequest
	/src/github.com/kkohtaka/gh-actions-pr-size/cmd/gh-actions-pr-size/github.go:126
main.main
	/src/github.com/kkohtaka/gh-actions-pr-size/cmd/gh-actions-pr-size/main.go:73
runtime.main
	/usr/local/go/src/runtime/proc.go:203
2022-05-04T01:29:17.263Z	FATAL	gh-actions-pr-size/main.go:75	Could not set a label to represent a pull request size	{"error": "add a label to a pull request: POST https://api.github.com/repos/tbd/tbd/issues/80/labels: 403 Resource not accessible by integration []"}
main.main
	/src/github.com/kkohtaka/gh-actions-pr-size/cmd/gh-actions-pr-size/main.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
```
**Actual result:** The exception `403 Resource not accessible by integration`
**Expected result:** No exception, the label related to size is set to pull request
**Workaround:** The GitHub action re-start leads to successful `kkohtaka/gh-actions-pr-size@v1.0.0` execution
**Similar case:** https://github.com/actions/first-interaction/issues/10#issuecomment-1041402989

**Comment by dgroup** [comment]
Checking that option with `pull-request: write` permission

**Comment by dgroup** [comment]
Thanks @kkohtaka , i've added the following lines
```yaml
jobs:
  estimate_pull_request:
    ...
    permissions:
      pull-requests: write
```
and today the build is successful for new PR with github-action update:
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1651114/166876001-89c7ffab-1ddb-4337-b46e-4f8961a41f3b.png">
